### ISSUE TITLE
Does alf support emitting invoices? 

### ISSUE THREAD

**Issue by ieugen** [exteso/alf.io#104] opened 2016-03-04 11:00 UTC
Hi, 

I am considering alf for a customer and I was wondering if alf is able to emit invoices to customers. Either automate or manual. 

Is not, can it be extended easily for that? 

p.s. The heroku deployment did not work for me. The authentication doesn't seem to work the second time but it does not issue a failed login message. It just redisplays the login page and I'm locked out of the application. I also istalled it locally but hit the https redirect which causes problems in my local tomcat instance. I believe the proper approach is to let the ssl handling to a proxy or implement it via other mechanisms than a filter.

The login issue is caused by heroku closing the app because of inactivity so the single page app does not have a back-end to send requests to. This should cause an error on the client side, but I guess heroku does not respond properly or something.  Visiting the appplication root causes the app to restart and authentication succeeds. 

p.s.2 the java version check failed on my machine (Debian 8) with openjdk-8 from backports. I removed it and it built ok. I would just remove that part and document the minimum java & jdk version required. Gradle has 
````
sourceCompatibility = 1.8
targetCompatibility = 1.8 
````
https://docs.gradle.org/current/userguide/java_plugin.html

**Comment by cbellone** [comment] 2016-03-06 15:46
Hi @ieugen,
thanks for using alf.io!

Below you can find my answers

 > I am considering alf for a customer and I was wondering if alf is able to emit invoices to customers. Either automate or manual.

great! At the moment alf.io will generate a payment receipt (PDF) at the end of the booking process. In some use cases (including our own) that's enough.

> Is not, can it be extended easily for that?

yes and no. 
There is a very simple plugin mechanism (see https://github.com/exteso/alf.io/blob/master/src/main/java/alfio/plugin/Plugin.java and https://github.com/exteso/alf.io/blob/master/src/main/java/alfio/plugin/mailchimp/MailChimpPlugin.java for reference) but is intended for general-purpose plugins (such as mailing list, etc.). 
This means that you can still fork the project and implement your own plugins to cover your needs (invoice, etc.) but for most of them it wouldn't make sense to be merged into the master branch.

What we're really missing here is an external plugin mechanism, so that you could implement your plugins and then load them directly from a running instance of alf.io. Unfortunately this is not (yet) on our roadmap, so it would be great if you could do a pull request for that or, since you're considering it for business, help the project paying for the effort needed for the implementation.

what do you think about?


> p.s. The heroku deployment did not work for me. The authentication doesn't seem to work the second time but it does not issue a failed login message. It just redisplays the login page and I'm locked out of the application. I also istalled it locally but hit the https redirect which causes problems in my local tomcat instance. I believe the proper approach is to let the ssl handling to a proxy or implement it via other mechanisms than a filter.

please consult the readme for running alf.io on your machine. If you run in production mode, SSL can't be disabled, this is not a bug.

> The login issue is caused by heroku closing the app because of inactivity so the single page app does not have a back-end to send requests to. This should cause an error on the client side, but I guess heroku does not respond properly or something. Visiting the appplication root causes the app to restart and authentication succeeds.

could you please open another issue for this? If possible, please explain all the steps to reproduce the problem. Thank you for that. 

> p.s.2 the java version check failed on my machine (Debian 8) with openjdk-8 from backports. I removed it and it built ok. I would just remove that part and document the minimum java & jdk version required. Gradle has
> sourceCompatibility = 1.8
> targetCompatibility = 1.8 
> https://docs.gradle.org/current/userguide/java_plugin.html

that wouldn't be enough. There was a bug in the type inference mechanism of older versions of java compiler (< 1.8.25, see #57). That's why is mandatory to compile alf.io with javac v.1.8.0b25+

cheers,
Celestino

**Comment by treed593** [comment] 2016-04-13 02:10
When it comes to the Heroku login issue check out #116 the fix there worked for me

**Closed** 2016-05-14 20:02 UTC
